# Generated by Django 6.0.3 on 2026-05-02 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user_order_number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
